'use strict';

const path = require('path');
const fs = require('fs');
const { parseFrontmatter, ensureDir } = require('../util');

const loadModuleBody = (sourceDir, mod) => {
  const filePath = path.join(sourceDir, mod.file);
  const raw = fs.readFileSync(filePath, 'utf8');
  const { body } = parseFrontmatter(raw);
  return body;
};

const syncAgentsMd = ({ cwd, modules, moduleDefs, sourceDir, manifest }) => {
  const outFile = path.join(cwd, 'AGENTS.md');
  const lines = [
    '# JianghuJS AI Development Rules',
    '',
    '> Generated by `jianghu-init dev-rules`. Canonical source: `.jianghu/ai-rules/source/`',
    '',
    `- Profile: \`${manifest.profile}\``,
    `- Targets: ${manifest.targets.map(t => `\`${t}\``).join(', ')}`,
    `- Last sync: ${manifest.lastSyncAt}`,
    '',
    '## Modules',
    '',
  ];

  for (const modId of modules) {
    const def = moduleDefs[modId];
    if (!def) continue;
    lines.push(`### ${def.title || modId}`);
    lines.push('');
    if (def.description) {
      lines.push(def.description);
      lines.push('');
    }
    lines.push(`- Source: \`.jianghu/ai-rules/source/${def.file}\``);
    lines.push('');
    const body = loadModuleBody(sourceDir, def);
    const preview = body.split('\n').slice(0, 8).join('\n');
    lines.push('<details>');
    lines.push(`<summary>${modId}</summary>`);
    lines.push('');
    lines.push(preview);
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('## Update');
  lines.push('');
  lines.push('```bash');
  lines.push('jianghu-init dev-rules --sync');
  lines.push('jianghu-init dev-rules --sync --force');
  lines.push('```');
  lines.push('');

  fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
  return ['AGENTS.md'];
};

module.exports = {
  id: 'agents-md',
  label: 'AGENTS.md (cross-tool index)',
  sync: syncAgentsMd,
};
