'use strict';

const path = require('path');
const fs = require('fs');
const { parseFrontmatter, ensureDir } = require('../util');

const splitScope = scope => {
  if (!scope) return [];
  if (Array.isArray(scope)) return scope;
  return String(scope).split(',').map(s => s.trim()).filter(Boolean);
};

const loadModuleBody = (sourceDir, mod) => {
  const filePath = path.join(sourceDir, mod.file);
  const raw = fs.readFileSync(filePath, 'utf8');
  const { body } = parseFrontmatter(raw);
  return body;
};

const syncClaude = ({ cwd, modules, moduleDefs, sourceDir, force }) => {
  const rulesDir = path.join(cwd, '.claude', 'rules');
  ensureDir(rulesDir);
  const written = [];

  for (const modId of modules) {
    const def = moduleDefs[modId];
    if (!def) continue;
    const body = loadModuleBody(sourceDir, def);
    const outFile = path.join(rulesDir, `${modId}.md`);
    if (fs.existsSync(outFile) && !force) continue;

    const lines = ['---'];
    if (def.always) {
      lines.push('# unconditional rule');
    } else {
      const paths = splitScope(def.scope);
      if (paths.length) {
        lines.push('paths:');
        for (const p of paths) {
          lines.push(`  - ${JSON.stringify(p)}`);
        }
      }
    }
    lines.push('---', '', body, '');
    fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
    written.push(path.relative(cwd, outFile));
  }

  const claudeMd = path.join(cwd, 'CLAUDE.md');
  if (force || !fs.existsSync(claudeMd)) {
    const content = [
      '# JianghuJS Project Instructions',
      '',
      'Read `@AGENTS.md` for AI rule index.',
      '',
      'Modular rules live in `.claude/rules/` (generated by `jianghu-init dev-rules --sync`).',
      '',
      'Canonical source: `.jianghu/ai-rules/source/`',
      '',
      '## Quick commands',
      '',
      '- Update AI rules: `jianghu-init dev-rules --sync`',
      '- V7 smoke test (in jianghu-init): `node lib/json/v7/pages/examples/smoke-platform-layout.js`',
      '',
    ].join('\n');
    fs.writeFileSync(claudeMd, content, 'utf8');
    written.push('CLAUDE.md');
  }

  return written;
};

module.exports = {
  id: 'claude',
  label: 'Claude Code (CLAUDE.md + .claude/rules/)',
  sync: syncClaude,
};
