'use strict';

const path = require('path');
const { getRulePack } = require('../rulePacks');
const { getSkillsForRuleIds, syncSkillsToDirectory } = require('../skills');
const { createSyncResult, mergeSyncResult, syncTextFile } = require('../util');

const buildAgentsMd = ({ manifest, skills = [] }) => {
  const packs = (manifest.ruleIds || []).map(getRulePack).filter(Boolean);
  const lines = [
    '# JianghuJS Codex Instructions',
    '',
    '> Generated by `jianghu-init dev-rules`. Keep this entry concise; detailed workflows live under `.ai-rules/`.',
    '',
    `- Rule packs: ${packs.map(p => `\`${p.id}\``).join(', ')}`,
    `- Targets: ${manifest.targets.map(t => `\`${t}\``).join(', ')}`,
    `- Last sync: ${manifest.lastSyncAt}`,
    '',
    '## Project Rules',
    '',
    '- This is a JianghuJS application project.',
    '- Prefer existing project conventions, naming, folder layout, and framework patterns.',
    '- Do not introduce unrelated frameworks or broad rewrites unless explicitly requested.',
    '- Treat generated files as generated output unless the task explicitly asks to edit them.',
    '',
    '## Rule Pack Routing',
    '',
    'Read `.ai-rules/index.md` first, then load only the rule pack that matches the task:',
    '',
  ];

  for (const pack of packs) {
    lines.push(`- ${pack.label}: \`.ai-rules/${pack.id}/README.md\``);
  }

  if (skills.length) {
    lines.push('');
    lines.push('## Task Skills');
    lines.push('');
    lines.push('Use the matching skill for the task. Read its `SKILL.md` before making changes:');
    lines.push('');
    for (const skill of skills) {
      lines.push(`- ${skill.label}: \`.agents/skills/${skill.id}/SKILL.md\``);
    }
  }

  lines.push('');
  lines.push('## Update');
  lines.push('');
  lines.push('```bash');
  lines.push(`jianghu-init dev-rules --rule=${(manifest.ruleIds || []).join(',')} --target=${(manifest.targets || ['codex']).join(',')} --force`);
  lines.push('```');
  lines.push('');

  return lines.join('\n');
};

const syncCodex = ({ cwd, manifest, templateRoot, force, managedFiles }) => {
  const skills = getSkillsForRuleIds(templateRoot, manifest.ruleIds);
  const result = createSyncResult();
  const skillResult = syncSkillsToDirectory({
    cwd,
    templateRoot,
    skills,
    targetRoot: path.join(cwd, '.agents', 'skills'),
    force,
    managedFiles,
  });
  mergeSyncResult(result, skillResult);
  const outFile = path.join(cwd, 'AGENTS.md');
  syncTextFile({
    cwd,
    filePath: outFile,
    content: buildAgentsMd({ manifest, skills }),
    force,
    managedFiles,
    result,
  });
  return result;
};

module.exports = {
  id: 'codex',
  label: 'Codex (AGENTS.md)',
  sync: syncCodex,
  buildAgentsMd,
};
