'use strict';

const path = require('path');
const fs = require('fs');
const { ensureDir, parseFrontmatter } = require('./util');

const RULE_PACKS = {
  'jianghu-init-json-app': {
    id: 'jianghu-init-json-app',
    label: 'JianghuJS init-json app',
    description: 'JianghuJS 业务 app：app/view/init-json 页面与组件开发规范',
    globs: [
      'app/view/init-json/**/*.js',
      'app/view/page/**/*.html',
      'app/view/component/**/*.html',
    ],
    files: [
      { dest: 'README.md', title: 'JianghuJS init-json app', source: 'source/overview.md' },
      { dest: 'v7-crud-authoring.md', source: 'source/v7-crud-authoring.md' },
      { dest: 'jh-component.md', source: 'source/jh-component.md' },
      { dest: 'v7-app-authoring.md', source: 'docs/v7-app-authoring.md' },
    ],
  },
  'jianghu-seo-app': {
    id: 'jianghu-seo-app',
    label: 'OpenJianghu SEO app',
    description: 'OpenJianghu SEO 文档站：xfPage/article/category/meilisearch/template 开发规范',
    globs: [
      'app/view/page/**/*.html',
      'app/view/xfpageTemplate/**/*.html',
      'app/view/template/**/*.html',
      'app/service/**/*.js',
      'app/controller/**/*.js',
      'config/**/*.js',
      'meilisearchScript/**/*',
    ],
    files: [
      { dest: 'README.md', source: 'packs/jianghu-seo-app/README.md' },
      { dest: 'workflow.md', source: 'packs/jianghu-seo-app/workflow.md' },
      { dest: 'seo-checklist.md', source: 'packs/jianghu-seo-app/seo-checklist.md' },
    ],
  },
};

const normalizeRuleId = id => {
  if (id === 'init-json-app' || id === 'app' || id === 'jianghu-app') return 'jianghu-init-json-app';
  if (id === 'seo-app' || id === 'openjianghu-seo') return 'jianghu-seo-app';
  return id;
};

const parseRuleIds = raw => {
  if (!raw) return [];
  return String(raw)
    .split(',')
    .map(s => normalizeRuleId(s.trim()))
    .filter(Boolean);
};

const listRulePacks = () => Object.values(RULE_PACKS).map(({ id, label, description }) => ({
  id,
  label,
  description,
}));

const getRulePack = id => RULE_PACKS[normalizeRuleId(id)];

const readSourceBody = (templateRoot, source) => {
  const filePath = path.join(templateRoot, source);
  const raw = fs.readFileSync(filePath, 'utf8');
  return parseFrontmatter(raw).body;
};

const buildPackReadme = (pack, body) => [
  `# ${pack.label}`,
  '',
  `> Generated by \`jianghu-init dev-rules\`. Rule pack id: \`${pack.id}\`.`,
  '',
  body,
  '',
].join('\n');

const syncRulePacks = ({ cwd, ruleIds, templateRoot, force }) => {
  const baseDir = path.join(cwd, '.ai-rules');
  ensureDir(baseDir);
  const written = [];
  const skipped = [];
  const selected = ruleIds.map(getRulePack).filter(Boolean);

  const indexFile = path.join(baseDir, 'index.md');
  if (force || !fs.existsSync(indexFile)) {
    const lines = [
      '# AI Rule Packs',
      '',
      '> Generated by `jianghu-init dev-rules`. These files are shared references for Codex, Cursor, Kiro, Claude Code, and other AI tools.',
      '',
      '## Selected Packs',
      '',
    ];
    for (const pack of selected) {
      lines.push(`- [${pack.label}](./${pack.id}/README.md): ${pack.description}`);
    }
    lines.push('');
    lines.push('## Usage');
    lines.push('');
    lines.push('- Project entry files should stay concise and route AI tools here for detailed workflows.');
    lines.push('- Use the rule pack that matches the task. Do not load unrelated packs by default.');
    lines.push('- Update with `jianghu-init dev-rules --force`.');
    lines.push('');
    fs.writeFileSync(indexFile, lines.join('\n'), 'utf8');
    written.push('.ai-rules/index.md');
  } else {
    skipped.push('.ai-rules/index.md');
  }

  for (const pack of selected) {
    const packDir = path.join(baseDir, pack.id);
    ensureDir(packDir);
    for (const file of pack.files) {
      const outFile = path.join(packDir, file.dest);
      if (fs.existsSync(outFile) && !force) {
        skipped.push(path.relative(cwd, outFile));
        continue;
      }
      const body = readSourceBody(templateRoot, file.source);
      const content = file.dest === 'README.md' ? buildPackReadme(pack, body) : `${body}\n`;
      fs.writeFileSync(outFile, content, 'utf8');
      written.push(path.relative(cwd, outFile));
    }
  }

  if (!written.length && skipped.length) return { skipped };
  return written;
};

module.exports = {
  getRulePack,
  listRulePacks,
  parseRuleIds,
  syncRulePacks,
};
