'use strict';

const path = require('path');
const fs = require('fs');
const {
  ensureDir, parseFrontmatter, createSyncResult, mergeSyncResult, syncTextFile,
} = require('./util');
const { getSkillsForRuleIds, syncSkillsToDirectory } = require('./skills');

const RULE_PACKS = {
  'jianghu-init-json-app': {
    id: 'jianghu-init-json-app',
    label: 'JianghuJS init-json app',
    description: 'JianghuJS 业务 app：app/view/init-json 页面与组件开发规范',
    globs: [
      'app/view/init-json/**/*.js',
      'app/view/page/**/*.html',
      'app/view/component/**/*.html',
    ],
    files: [
      { dest: 'README.md', title: 'JianghuJS init-json app', source: 'source/overview.md' },
      { dest: 'v7-crud-authoring.md', source: 'source/v7-crud-authoring.md' },
      { dest: 'v7-crud-full-structure.md', source: 'docs/v7-crud-full-structure.md' },
      { dest: 'jh-component.md', source: 'source/jh-component.md' },
      { dest: 'v7-app-authoring.md', source: 'docs/v7-app-authoring.md' },
      { dest: 'agent-workflow.md', source: 'packs/jianghu-init-json-app/quality/agent-workflow.md' },
      { dest: 'coding-standards.md', source: 'packs/jianghu-init-json-app/quality/coding-standards.md' },
      { dest: 'review-prompt-template.md', source: 'packs/jianghu-init-json-app/quality/review-prompt-template.md' },
      { dest: 'config-reference.md', source: '../json/v7/docs/config-reference.md' },
      { dest: 'authoring-guide.md', source: '../json/v7/docs/authoring-guide.md' },
      { dest: 'semantic-to-component-mapping.md', source: '../json/v7/docs/semantic-to-component-mapping.md' },
      { dest: 'bind-slots-and-targets.md', source: '../json/v7/docs/bind-slots-and-targets.md' },
      {
        dest: 'examples-guide.md',
        source: '../json/v7/docs/examples-guide.md',
        transform: body => body.replace(
          'lib/json/v7/pages/examples/',
          '.ai-rules/jianghu-init-json-app/examples/',
        ),
      },
      { dest: 'examples/projectManagement.v7.sample.js', source: '../json/v7/pages/examples/projectManagement.v7.sample.js' },
      { dest: 'examples/fullCrudPage.v7.example.js', source: '../json/v7/pages/examples/fullCrudPage.v7.example.js' },
      { dest: 'examples/fullUiPage.v7.example.js', source: '../json/v7/pages/examples/fullUiPage.v7.example.js' },
      { dest: 'examples/taskSubTable.v7.component.crud.sample.js', source: '../json/v7/pages/examples/taskSubTable.v7.component.crud.sample.js' },
      { dest: 'examples/projectSummaryCard.v7.component.ui.sample.js', source: '../json/v7/pages/examples/projectSummaryCard.v7.component.ui.sample.js' },
      { dest: 'examples/fullComponentCrud.v7.example.js', source: '../json/v7/pages/examples/fullComponentCrud.v7.example.js' },
      { dest: 'examples/fullComponentUi.v7.example.js', source: '../json/v7/pages/examples/fullComponentUi.v7.example.js' },
    ],
  },
  'jianghu-seo-app': {
    id: 'jianghu-seo-app',
    label: 'OpenJianghu SEO app',
    description: 'OpenJianghu SEO 文档站：xfPage/article/category/meilisearch/template 开发规范',
    globs: [
      'app/view/page/**/*.html',
      'app/view/xfpageTemplate/**/*.html',
      'app/view/template/**/*.html',
      'app/service/**/*.js',
      'app/controller/**/*.js',
      'config/**/*.js',
      'meilisearchScript/**/*',
    ],
    files: [
      { dest: 'README.md', source: 'packs/jianghu-seo-app/README.md' },
      { dest: 'workflow.md', source: 'packs/jianghu-seo-app/workflow.md' },
      { dest: 'seo-checklist.md', source: 'packs/jianghu-seo-app/seo-checklist.md' },
    ],
  },
};

const PROJECT_TEMPLATE_DIR = 'packs/jianghu-init-json-app/project';
const PROJECT_TEMPLATE_FILES = [
  'README.md',
];

const normalizeRuleId = id => {
  if (id === 'init-json-app' || id === 'app' || id === 'jianghu-app') return 'jianghu-init-json-app';
  if (id === 'seo-app' || id === 'openjianghu-seo') return 'jianghu-seo-app';
  return id;
};

const parseRuleIds = raw => {
  if (!raw) return [];
  return String(raw)
    .split(',')
    .map(s => normalizeRuleId(s.trim()))
    .filter(Boolean);
};

const listRulePacks = () => Object.values(RULE_PACKS).map(({ id, label, description }) => ({
  id,
  label,
  description,
}));

const getRulePack = id => RULE_PACKS[normalizeRuleId(id)];

const readSourceBody = (templateRoot, source, transform) => {
  const filePath = path.join(templateRoot, source);
  const raw = fs.readFileSync(filePath, 'utf8');
  const body = parseFrontmatter(raw).body;
  return transform ? transform(body) : body;
};

const buildPackReadme = (pack, body) => [
  `# ${pack.label}`,
  '',
  `> Generated by \`jianghu-init dev-rules\`. Rule pack id: \`${pack.id}\`.`,
  '',
  body,
  '',
].join('\n');

const ensureProjectTemplates = ({ cwd, templateRoot, ruleIds }) => {
  if (!(ruleIds || []).includes('jianghu-init-json-app')) return;
  const projectDir = path.join(cwd, '.ai-rules', 'project');
  ensureDir(projectDir);
  for (const file of PROJECT_TEMPLATE_FILES) {
    const dest = path.join(projectDir, file);
    if (fs.existsSync(dest)) continue;
    const source = path.join(templateRoot, PROJECT_TEMPLATE_DIR, file);
    fs.copyFileSync(source, dest);
  }
};

const syncRulePacks = ({ cwd, ruleIds, templateRoot, force, managedFiles }) => {
  const baseDir = path.join(cwd, '.ai-rules');
  ensureDir(baseDir);
  const result = createSyncResult();
  const selected = ruleIds.map(getRulePack).filter(Boolean);
  const hasInitJsonPack = ruleIds.includes('jianghu-init-json-app');

  const indexFile = path.join(baseDir, 'index.md');
  const lines = [
      '# AI Rule Packs',
      '',
      '> Generated by `jianghu-init dev-rules`. These files are shared references for Codex, Cursor, Kiro, Claude Code, and other AI tools.',
      '',
      '## Selected Packs',
      '',
    ];
  for (const pack of selected) {
    lines.push(`- [${pack.label}](./${pack.id}/README.md): ${pack.description}`);
  }
  lines.push('');
  lines.push('## Usage');
  lines.push('');
  lines.push('- Project entry files should stay concise and route AI tools here for detailed workflows.');
  if (hasInitJsonPack) {
    lines.push('- Read `.ai-rules/project/README.md` for project-owned business knowledge; it is never overwritten by dev-rules.');
    lines.push('- Before init-json changes, read `.ai-rules/jianghu-init-json-app/coding-standards.md`; follow `.ai-rules/jianghu-init-json-app/agent-workflow.md` for L0/L1/L2/L3 quality boundaries.');
    lines.push('- For a page task, also read `.ai-rules/project/pages/<pageId>.md` when it exists.');
  }
  lines.push('- Use the rule pack that matches the task. Do not load unrelated packs by default.');
  lines.push('- Update with `jianghu-init dev-rules --force`.');
  const skills = getSkillsForRuleIds(templateRoot, ruleIds);
  if (skills.length) {
    lines.push('');
    lines.push('## Task Skills');
    lines.push('');
    for (const skill of skills) {
      lines.push(`- [${skill.label}](./skills/${skill.id}/SKILL.md): ${skill.description}`);
    }
  }
  lines.push('');
  syncTextFile({ cwd, filePath: indexFile, content: lines.join('\n'), force, managedFiles, result });
  ensureProjectTemplates({ cwd, templateRoot, ruleIds });

  for (const pack of selected) {
    const packDir = path.join(baseDir, pack.id);
    ensureDir(packDir);
    for (const file of pack.files) {
      const outFile = path.join(packDir, file.dest);
      const body = readSourceBody(templateRoot, file.source, file.transform);
      const content = file.dest === 'README.md' ? buildPackReadme(pack, body) : `${body}\n`;
      syncTextFile({ cwd, filePath: outFile, content, force, managedFiles, result });
    }
  }

  const skillResult = syncSkillsToDirectory({
    cwd,
    templateRoot,
    skills,
    targetRoot: path.join(baseDir, 'skills'),
    force,
    managedFiles,
  });
  mergeSyncResult(result, skillResult);
  return result;
};

module.exports = {
  getRulePack,
  listRulePacks,
  parseRuleIds,
  syncRulePacks,
};
